name: Download Twitch VOD and Upload to YouTube
on:
  repository_dispatch:
    types: [process-vod]

jobs:
  process-vod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Free up disk space
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yt-dlp google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests
          
      - name: Install TwitchDownloaderCLI
        run: |
          wget https://github.com/lay295/TwitchDownloader/releases/download/1.56.4/TwitchDownloaderCLI-1.56.4-Linux-x64.zip
          unzip TwitchDownloaderCLI-1.56.4-Linux-x64.zip
          chmod +x TwitchDownloaderCLI

      - name: Download VOD with yt-dlp
        run: |
          echo "--- STARTING DOWNLOAD ---"

          yt-dlp \
            --no-progress \
            --no-warnings \
            --quiet \
            -f "bestvideo[height<=720]+bestaudio/best[height<=720]" \
            -N 4 \
            --merge-output-format mp4 \
            -o "video_temp.mp4" \
            "https://www.twitch.tv/videos/${{ github.event.client_payload.vod_id }}"

      - name: Download chat log with TwitchDownloaderCLI
        run: |
          echo "--- DOWNLOADING CHAT LOG ---"
          ./TwitchDownloaderCLI chatdownload \
            -u ${{ github.event.client_payload.vod_id }} \
            -o "chat.json"
          
      - name: Send chat to Discord
        run: |
          python send_chat_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Upload VOD to YouTube
        run: |
          export VIDEO_TITLE="${{ github.event.client_payload.video_title }}"
          export TWITCH_URL="https://www.twitch.tv/videos/${{ github.event.client_payload.vod_id }}"
          python upload.py
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}